# Generated by Django 2.2.1 on 2019-05-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeiro_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('cargo', models.CharField(choices=[('SRV', 'Servidor'), ('PRF', 'Professor')], default='SRV', max_length=3)),
                ('contratacao', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Servidores',
            },
        ),
    ]
