# Generated by Django 2.2.1 on 2019-05-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20190520_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfazer',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
